# Generated by Django 6.0.4 on 2026-05-05
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('camera', 'Camera')], max_length=20)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('model_config', models.JSONField(blank=True, default=dict)),
                ('camera_config', models.JSONField(blank=True, default=dict)),
                ('last_results', models.JSONField(blank=True, default=dict)),
                ('last_media_path', models.CharField(blank=True, max_length=255)),
                ('last_media_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
