# Generated by Django 6.0.4 on 2026-05-05
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DangerousObjectDetection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # NOTE:
    # This migration was generated after a previous iteration where `owner`
    # and `camera_config` were introduced after the initial model creation.
    # In the current codebase, `0001_initial` already includes those fields.
    # Keeping AddField operations here causes SQLite to error with:
    #   duplicate column name: owner_id
    #
    # We keep the migration file (and number) to preserve a stable migration
    # history, but make it a no-op.
    operations = []
