"""
Django settings for shelter_safety project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-01lyre=6aed2575(6m4lhw0@rm4l^c1bloms@ck-w0lgk9v8ei'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'blessures_app',
    'violence_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shelter_safety.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shelter_safety.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# CONFIGURATION DES MODÈLES DE BLESSURES
# ============================================================

# Chemins des modèles
MODELS_DIR = BASE_DIR / 'blessures_app' / 'models'
VIOLENCE_MAIN_MODEL = BASE_DIR / 'models' / 'violence' / 'best_main_model.pt'
VIOLENCE_YOLO_MODEL = BASE_DIR / 'models' / 'violence' / 'yolo26n.pt'
VIOLENCE_MEDIAPIPE_MODEL = BASE_DIR / 'models' / 'violence' / 'best_pose_mlp.pt'
MODEL_WEIGHTS_PATH = VIOLENCE_MAIN_MODEL

# Paramètres des modèles de classification
URGENT_THRESHOLD = 0.35
IMG_SIZE = 224

# Paramètres YOLO
YOLO_CONF_THRESHOLD = 0.20

# Paramètres segmentation
SEG_IMG_SIZE = 256

# Classes
URGENCY_CLASSES = ['Urgent', 'Non-Urgent', 'Incertain']
URGENCY_EMOJI = {0: '🔴 Urgent', 1: '🟢 Non-Urgent', 2: '🟡 Incertain'}
URGENCY_COLORS = {0: '#e74c3c', 1: '#27ae60', 2: '#f39c12'}

INJURY_TO_URGENCY = {
    'burn': 0,
    'cut': 0,
    'laceration': 0,
    'infected': 0,
    'abrasion': 1,
    'bruise': 1,
    'rash': 2,
}

MODEL_CACHE_TIMEOUT = 3600
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')